version: '2'
services:
  teamangusfantasyfootball-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/TeamAngusFantasyFootball/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=TeamAngusFantasyFootball
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
